site_name: TLIBEs

theme:
  name: material
  palette:
    primary: black
  features:
    - navigation.instant
    - navigation.indexes
    - content.code.annotate

nav: 
  - 案例库: 
    - cases/index.md
    - 2021秋季系列调研: cases/survey2021A.md
    - 2022春季操作系统课程调研: cases/OS2022S.md
    - 2022春季网络原理后续课程梳理: cases/network2022S.md
  - 课咨委之始: beginning/index.md
  - 方法的局限: methods/index.md
  - 专题梳理: 
    - topics/index.md
    - 课程改进共同体: topics/improve.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
